spring:
  datasource:
    url: jdbc:mysql://yamabiko.proxy.rlwy.net:42002/railway
    username: root
    password: OGWidIOLQWlVCHywtIbOzDvPhWbsoAtC
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
