server:
  port: 8080
  servlet:
    context-path: /share-edu

spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/shareEdu"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 462004
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "nJ5IePEJ+FXEQCl/LnyQEI2W/VU0cFv+NjsT35m8+e2B/My+7is+DJqmmSutYfIr"
  valid-duration: 360000 # second
  refreshable-duration: 3600000 #in second