server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /share-edu

spring:
  datasource:
    url: ${mysql://root:SgVGCyucZqTAyhONErVslYOiIcawiEQj@gondola.proxy.rlwy.net:45224/railway}
    username: ${root}
    password: ${SgVGCyucZqTAyhONErVslYOiIcawiEQj}
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "nJ5IePEJ+FXEQCl/LnyQEI2W/VU0cFv+NjsT35m8+e2B/My+7is+DJqmmSutYfIr"
  valid-duration: 360000
  refreshable-duration: 3600000
