server:
  port: ${PORT:8080}
  servlet:
    context-path: /share-edu

spring:
  datasource:
    url: ${DB_URL}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: ${JWT_KEY}
  valid-duration: 360000
  refreshable-duration: 3600000
